eval_metric:
  name: BoundaryAdaptedRandError
  threshold: 0.4
  use_first_input: true
  use_last_target: true
loaders:
  label_internal_path: /label
  num_workers: 8
  raw_internal_path: /raw
  train:
    file_paths:
    - /g/kreshuk/wolny/Datasets/Ovules/train/N_226_ds2x.h5
    - /g/kreshuk/wolny/Datasets/Ovules/train/N_290_ds2x.h5
    - /g/kreshuk/wolny/Datasets/Ovules/train/N_291_ds2x.h5
    - /g/kreshuk/wolny/Datasets/Ovules/train/N_394_ds2x.h5
    - /g/kreshuk/wolny/Datasets/Ovules/train/N_396_ds2x.h5
    - /g/kreshuk/wolny/Datasets/Ovules/train/N_401_ds2x.h5
    - /g/kreshuk/wolny/Datasets/Ovules/train/N_403_ds2x.h5
    - /g/kreshuk/wolny/Datasets/Ovules/train/N_404_ds2x.h5
    - /g/kreshuk/wolny/Datasets/Ovules/train/N_405_A_ds2x.h5
    - /g/kreshuk/wolny/Datasets/Ovules/train/N_405_B_ds2x.h5
    - /g/kreshuk/wolny/Datasets/Ovules/train/N_416_ds2x.h5
    - /g/kreshuk/wolny/Datasets/Ovules/train/N_422_ds2x.h5
    - /g/kreshuk/wolny/Datasets/Ovules/train/N_425_ds2x.h5
    - /g/kreshuk/wolny/Datasets/Ovules/train/N_428_ds2x.h5
    - /g/kreshuk/wolny/Datasets/Ovules/train/N_434_ds2x.h5
    - /g/kreshuk/wolny/Datasets/Ovules/train/N_439_ds2x.h5
    - /g/kreshuk/wolny/Datasets/Ovules/train/N_440_ds2x.h5
    - /g/kreshuk/wolny/Datasets/Ovules/train/N_444_ds2x.h5
    - /g/kreshuk/wolny/Datasets/Ovules/train/N_445_ds2x.h5
    - /g/kreshuk/wolny/Datasets/Ovules/train/N_449_ds2x.h5
    - /g/kreshuk/wolny/Datasets/Ovules/train/N_450_ds2x.h5
    - /g/kreshuk/wolny/Datasets/Ovules/train/N_451_ds2x.h5
    - /g/kreshuk/wolny/Datasets/Ovules/train/N_454_ds2x.h5
    - /g/kreshuk/wolny/Datasets/Ovules/train/N_457_ds2x.h5
    - /g/kreshuk/wolny/Datasets/Ovules/train/N_458_ds2x.h5
    - /g/kreshuk/wolny/Datasets/Ovules/train/N_463_ds2x.h5
    - /g/kreshuk/wolny/Datasets/Ovules/train/N_473_ds2x.h5
    - /g/kreshuk/wolny/Datasets/Ovules/train/N_487_ds2x.h5
    - /g/kreshuk/wolny/Datasets/Ovules/train/N_494_ds2x.h5
    - /g/kreshuk/wolny/Datasets/Ovules/train/N_509_ds2x.h5
    - /g/kreshuk/wolny/Datasets/Ovules/train/N_512_ds2x.h5
    - /g/kreshuk/wolny/Datasets/Ovules/train/N_517_ds2x.h5
    - /g/kreshuk/wolny/Datasets/Ovules/train/N_525_ds2x.h5
    - /g/kreshuk/wolny/Datasets/Ovules/train/N_527_ds2x.h5
    - /g/kreshuk/wolny/Datasets/Ovules/train/N_530_ds2x.h5
    - /g/kreshuk/wolny/Datasets/Ovules/train/N_534_ds2x.h5
    - /g/kreshuk/wolny/Datasets/Ovules/train/N_535_ds2x.h5
    - /g/kreshuk/wolny/Datasets/Ovules/train/N_536_ds2x.h5
    - /g/kreshuk/wolny/Datasets/Ovules/train/N_563_ds2x.h5
    slice_builder:
      name: FilterSliceBuilder
      patch_shape:
      - 80
      - 170
      - 170
      slack_acceptance: 0.01
      stride_shape:
      - 20
      - 40
      - 40
      threshold: 0.6
    transformer:
      label:
      - name: RandomFlip
      - name: RandomRotate90
      - angle_spectrum: 20
        axes:
        - - 2
          - 1
        mode: reflect
        name: RandomRotate
      - name: ElasticDeformation
        spline_order: 0
      - append_label: true
        blur: true
        name: StandardLabelToBoundary
        sigma: 1.0
      - expand_dims: false
        name: ToTensor
      raw:
      - name: Standardize
      - name: RandomFlip
      - name: RandomRotate90
      - angle_spectrum: 20
        axes:
        - - 2
          - 1
        mode: reflect
        name: RandomRotate
      - name: ElasticDeformation
        spline_order: 3
      - expand_dims: true
        name: ToTensor
  val:
    file_paths:
    - /g/kreshuk/wolny/Datasets/Ovules/val/N_420_ds2x.h5
    - /g/kreshuk/wolny/Datasets/Ovules/val/N_464_ds2x.h5
    slice_builder:
      name: FilterSliceBuilder
      patch_shape:
      - 80
      - 170
      - 170
      slack_acceptance: 0.01
      stride_shape:
      - 80
      - 170
      - 170
      threshold: 0.4
    transformer:
      label:
      - append_label: true
        blur: true
        name: StandardLabelToBoundary
        sigma: 1.0
      - expand_dims: false
        name: ToTensor
      raw:
      - name: Standardize
      - expand_dims: true
        name: ToTensor
loss:
  ignore_index: null
  name: BCEWithLogitsLoss
  skip_last_target: true
lr_scheduler:
  factor: 0.2
  mode: min
  name: ReduceLROnPlateau
  patience: 15
manual_seed: 0
model:
  f_maps: 32
  final_sigmoid: true
  in_channels: 1
  layer_order: gcr
  name: UNet3D
  num_groups: 8
  out_channels: 1
optimizer:
  learning_rate: 0.0002
  weight_decay: 1.0e-05
trainer:
  checkpoint_dir: /g/kreshuk/wolny/workspace/plant-seg/plantseg/resources/training_configs/./grid_search/ovules/unet_gn_bce
  epochs: 1000
  eval_score_higher_is_better: false
  iters: 150000
  log_after_iters: 250
  resume: null
  validate_after_iters: 1000
